# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ubicacion', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
