# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 22:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Primer', '0003_lineas_multipunt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelitosMuni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delito', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=5, null=True)),
                ('subzona', models.CharField(blank=True, max_length=5, null=True)),
                ('subzona1', models.CharField(blank=True, max_length=5, null=True)),
                ('subzona2', models.CharField(blank=True, max_length=5, null=True)),
                ('mes', models.DateField()),
                ('punto', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
